In [2]:
# Q.1
import numpy as np

arr1 = np.random.randint(20,50,size = (2,3))
print(arr1)
print(arr1.shape)

[[23 21 32]
 [35 45 20]]
(2, 3)


In [9]:
# Q.2
arr2 = np.random.randint(1,100,size = (2,2,3))
print(arr2)
print(arr2.shape)

[[[48 69 61]
  [ 4 23  3]]

 [[58 90 67]
  [33 98 20]]]
(2, 2, 3)


In [13]:
# Q.3
# 2D

a1 = np.array([ [10,56,78,3],[19,56,77,88] ])
a2 = np.array([ [29,67,45,9],[100,66,77,88] ])
a3 = np.array([ [29,67,45,9], [100,66,77,88] ])

print(a1==a2)
print(a2==a3)
print(a1>a2)
print(a1<a2)
print(a1!=a2)
print(a1>=a2)
print(a1<=a2)
print(a2>=a3)

print(np.array_equal(a1,a2))
print(np.array_equal(a2,a3))
print(np.all(a1>a2))
print(np.all(a2==a3))
print(np.any(a1==a2))
print(np.any(a1>a2))
print(np.where(a1>a2))

[[False False False False]
 [False False  True  True]]
[[ True  True  True  True]
 [ True  True  True  True]]
[[False False  True False]
 [False False False False]]
[[ True  True False  True]
 [ True  True False False]]
[[ True  True  True  True]
 [ True  True False False]]
[[False False  True False]
 [False False  True  True]]
[[ True  True False  True]
 [ True  True  True  True]]
[[ True  True  True  True]
 [ True  True  True  True]]
False
True
False
True
True
True
(array([0]), array([2]))


In [15]:
# 3D

a1 = np.array([
   [[28,90,6,4,89],[23,17,56,3,8]],
    [[10,20,30,40,50],[1,2,3,6,8]],
])

a2 = np.array([
    [[19,70,6,4,0],[23,1,536,13,80]],
    [[12,23,10,0,50],[11,21,31,61,81]],
])

a3 = np.array([
    [[19,70,6,4,0],[23,1,536,13,80]],
    [[12,23,10,0,50],[11,21,31,61,81]],
])

print(a1==a2)
print(a2==a3)
print(a1>a2)
print(a1<a2)
print(a1!=a2)
print(a1>=a2)
print(a1<=a2)
print(a2>=a3)

print(np.array_equal(a1,a2))
print(np.array_equal(a2,a3))
print(np.all(a1>a2))
print(np.all(a2==a3))
print(np.any(a1==a2))
print(np.any(a1>a2))
print(np.where(a1>a2))

[[[False False  True  True False]
  [ True False False False False]]

 [[False False False False  True]
  [False False False False False]]]
[[[ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]]]
[[[ True  True False False  True]
  [False  True False False False]]

 [[False False  True  True False]
  [False False False False False]]]
[[[False False False False False]
  [False False  True  True  True]]

 [[ True  True False False False]
  [ True  True  True  True  True]]]
[[[ True  True False False  True]
  [False  True  True  True  True]]

 [[ True  True  True  True False]
  [ True  True  True  True  True]]]
[[[ True  True  True  True  True]
  [ True  True False False False]]

 [[False False  True  True  True]
  [False False False False False]]]
[[[False False  True  True False]
  [ True False  True  True  True]]

 [[ True  True False False  True]
  [ True  True  True  True  True]]]
[[[ True  True  True

In [35]:
# Q.4
arr_2d_2 = np.array([[10,20],[30,40],[50,60]])
print(arr_2d_2[1,0])
print(arr_2d_2[2,1])

print()

arr_3d_2 = np.array([
    [[10,20,30],[40,50,60]],
    [[70,80,90],[100,110,120]]
])

print(arr_3d_2[1,1,2])

30
60

120


In [3]:
# Q.5

a2 = np.array([
    [82,90,43,6,99],
    [78,99,35,6,44],
])

print(a2[a2>30])

[82 90 43 99 78 99 35 44]


In [10]:
a3 = np.array([
    [82,90,43,6,99],
    [78,99,35,6,44],
    [19,18,17,16,15],
    [110,236,789,462,931],
])

print(a3[a3>30])

[ 82  90  43  99  78  99  35  44 110 236 789 462 931]


In [21]:
a2d = np.array([
    [10,56,78,3],
    [1,2,3,4],
    [10,90,67,88]
])

print(a2d[2][a2d[2]>50])

[90 67 88]


In [34]:
a3d = np.array([
    [[28,90,6,4,89],[23,17,56,3,8]],
    [[10,20,30,40,50],[1,2,3,6,8]],
])

print(a3d[1,1][a3d[1,1]>5])

[6 8]
